name: curtain
description: A flutter dynamic responsive dashboard, easy to use and completely costumizable.
version: 0.0.2
homepage: https://github.com/EhsnJmli/curtain

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
